# -----------------------------------------------------------------------------
# Sets up automated image download, if enabled
# -----------------------------------------------------------------------------
img_auto_fetch = true

# -----------------------------------------------------------------------------
# if you set the time too early in the day, the API might not have the image yet.
# -----------------------------------------------------------------------------
time_to_fetch = 12:00:00

# -----------------------------------------------------------------------------
# directory where in users home directory images will be stored
# -----------------------------------------------------------------------------
image_dir = "Pictures/BingWallpapers"

# -----------------------------------------------------------------------------
# resize jpeg quality % defines thew size of the resized image. higher number -> better image, greater file size
# -----------------------------------------------------------------------------
store_jpg_quality = 89

# -----------------------------------------------------------------------------
# trim number of images collected always to this number: for 30 years = 10950 days
# -----------------------------------------------------------------------------
number_of_images_to_keep = 10950

# -----------------------------------------------------------------------------
# in case you want to uninstall the app, whether the you want to retain the images collected over time.
# -----------------------------------------------------------------------------
retain_images = true

# -----------------------------------------------------------------------------
# peapix is preferred service, since it allows to download better images from different countries
# -----------------------------------------------------------------------------
dl_service = "peapix"

# -----------------------------------------------------------------------------
# region used to download the bing images of the day. Acceptable regions see below in alt_peapix_region
# -----------------------------------------------------------------------------
region = "us"



# =============================================================================
[desktop_img]
# =============================================================================
# -----------------------------------------------------------------------------
# This feature works only on MacOS right now.
# if enabled the app will try to set the image as desktop. If false the image just going to be downloaded but not set as desktop image
# -----------------------------------------------------------------------------
enabled = true

# -----------------------------------------------------------------------------
# if height or width is configured to not supported size, it will be defaulted to 4K resolution: 3840x2160
# -----------------------------------------------------------------------------
width = 3840
height = 2160

# -----------------------------------------------------------------------------
# when downloaded the image will be resized to correct resolution of your screen. This is the jpeg quality setting when compressing by resizing.
# -----------------------------------------------------------------------------
jpg_quality = 80

# -----------------------------------------------------------------------------
# the alternative sizes are not configurable, there are here just for information what is supported
# -----------------------------------------------------------------------------
alt_dimension = [ {"width" = 640, "height" = 480}, {"width" = 1024, "height" = 768}, {"width" = 1600, "height" = 1200}, {"width" = 1920, "height" = 1080}, {"width" = 1920, "height" = 1200}, {"width" = 3840, "height" = 2160} ]



# =============================================================================
[constant]
# =============================================================================
# -----------------------------------------------------------------------------
# alternative download service. Peapix is preferred because it usually offers a better image quality.
# -----------------------------------------------------------------------------
alt_dl_service = ["bing", "peapix"]

# -----------------------------------------------------------------------------
# alternative regions for peapix service. Metadata will be also used from that region and added to the image.
# please do not change the order of the country codes, since it is used in the SQLite
# -----------------------------------------------------------------------------
alt_peapix_region = ["jp", "cn", "in", "es", "de", "it", "fr", "gb", "br", "ca", "us", "au"]

# -----------------------------------------------------------------------------
# Peapix API service URL
# -----------------------------------------------------------------------------
peapix_url = "https://peapix.com/bing/feed"

# -----------------------------------------------------------------------------
# alternative regions for peapix service. Metadata will be also used from that region and added to the image.
# -----------------------------------------------------------------------------
alt_bing_region = ["en-AU", "en-CA", "zh-CN", "de-DE", "fr-FR", "hi-IN", "ja-JP", "es-ES", "en-GB", "en-US"]
# -----------------------------------------------------------------------------
# Bing API service URL
# -----------------------------------------------------------------------------
bing_url = "http://www.bing.com/HPImageArchive.aspx"



# =============================================================================
[retry]
# =============================================================================
# -----------------------------------------------------------------------------
# Enable hourly retry mechanism for Frame TV uploads and desktop wallpaper setting
# When enabled, the app will retry every hour until success, then wait until next day
# -----------------------------------------------------------------------------
enabled = true

# -----------------------------------------------------------------------------
# Maximum number of retry attempts per day (24 = every hour)
# After this many attempts, wait until the next day
# -----------------------------------------------------------------------------
max_attempts_per_day = 12

# -----------------------------------------------------------------------------
# Time when daily retry counter resets (24-hour format)
# Set to early morning when TV is likely to be off
# -----------------------------------------------------------------------------
daily_reset_time = "06:00:00"

# -----------------------------------------------------------------------------
# Require all enabled operations to succeed before marking day as successful
# If false, partial success (e.g., download only) will stop retries
# -----------------------------------------------------------------------------
require_all_operations_success = true



# =============================================================================
[ftv]
# =============================================================================
# -----------------------------------------------------------------------------
# if true, images for each day will be produced and pushed to Samsung Frame TV. This is still WIP, though!
# -----------------------------------------------------------------------------
enabled = true

# -----------------------------------------------------------------------------
# if true - images will be copied to ftv_images_today folder (USB mass storage mode for Raspberry Pi)
# if false - images will be uploaded via HTTP/WebSocket (current implementation)
# -----------------------------------------------------------------------------
usb_mode = true

# -----------------------------------------------------------------------------
# 70-100. JPEG quality used when resizing to Samsung Frame TV size (3810x2160).
# Lower number - lower quality image but smaller file size, larger number better quality larger file sizes
# The image size for ftv is stored in the native 3840x2160 (4K) format.
# This cannot be changed, because it is the native resolution for Frame TV
# -----------------------------------------------------------------------------
jpg_quality = 80

# -----------------------------------------------------------------------------
# frame tv secret data file in toml format. This file should not be committed to git
# -----------------------------------------------------------------------------
ftv_data = "ftv_data.toml"
