[ftv_data]
# -----------------------------------------------------------------------------
# Frame TVs data, corresponds to the class FTVData
#   - api_token: Samsung's security api token, needed to be able to talk to TV. It could be:
#       - file name: where the api token is stored. Do not commit to GIT
#   - img_rate: frequency in seconds the image should change on Frame TV
#   - ip: ip address, where Frame TV is on local network
#   - mac: mac address of the Frame TV network card, needed to send magic package to wake up TV
#   - port: port on which the Frame TV is on, usually 8001
# -----------------------------------------------------------------------------
    [ftv_data.name_of_your_tv1]
    image_updates = true
    auth_token_file = "name_of_your_tv1_authToken_secrets.txt"
    img_rate = 300
    ip_addr = "192.168.0.39"
    mac_addr = "XX-XX-XX-XX-XX-XX"
    port = 8002

    [ftv_data.name_of_your_tv2]
    image_updates = false
    auth_token_file = "name_of_your_tv2_authToken_secrets.txt"
    img_rate = 400
    ip_addr = "192.168.100.45"
    mac_addr = "XX-XX-XX-XX-XX-XX"
    port = 8045

    [ftv_data.name_of_your_tv3]
    image_updates = false
    auth_token_file = "name_of_your_tv3_authToken_secrets.txt"
    img_rate = 500
    ip_addr = "192.168.100.42"
    mac_addr = "XX-XX-XX-XX-XX-XX"
    port = 8042
