[ftv_data]
# -----------------------------------------------------------------------------
# Frame TVs data. Configure as many TV as you want to control. In this case 3 Frame TVs
#   - img_rate: frequency in seconds the image should change on Frame TV. e.g: 5 min: 5*60 = 300
#   - ip: ip address, where Frame TV is on local network
#   - mac: mac address of the Frame TV network card, needed to send magic package to wake up TV
#   - port: port on which the Fram TV is on, usually 8001
# -----------------------------------------------------------------------------
    [ftv_data.name_of_your_tv1]
    img_rate = 300
    ip_addr = "192.168.100.39"
    mac_addr = "XX-XX-XX-XX-XX-XX"
    port = 8001

    [ftv_data.name_of_your_tv2]
    img_rate = 400
    ip_addr = "192.168.100.45"
    mac_addr = "XX-XX-XX-XX-XX-XX"
    port = 8045

    [ftv_data.name_of_your_tv3]
    img_rate = 500
    ip_addr = "192.168.100.42"
    mac_addr = "XX-XX-XX-XX-XX-XX"
    port = 8042
