version: 1
disable_existing_loggers: True

formatters:
    abkFormatterShort:
        format: '[%(asctime)s]:[%(module)s.%(funcName)s]:[%(levelname)s]: %(message)s'
        datefmt: '%Y%m%d %H:%M:%S'
    abkFormatterLong:
        format: '[%(asctime)s]:[%(thread)d]:[%(module)s.%(funcName)s]:[%(name)s][%(levelname)s]: %(message)s'
        datefmt: '%Y%m%d %H:%M:%S'

handlers:
    consoleHandler:
        class: logging.StreamHandler
        level: DEBUG
        formatter: abkFormatterShort
        stream: ext://sys.stdout
    fileHandler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: abkFormatterLong
        filename: logs/bingwallpaper.log
        maxBytes: 10485760
        backupCount: 5
        encoding: utf-8
        delay: true
        mode: a
    queueHandler:
        class: logging.handlers.QueueHandler
        handlers:
          - consoleHandler
          - fileHandler
        queue: ext://queue.Queue
        respect_handler_level: true

loggers:
    root:
        level: DEBUG
        handlers:
          - consoleHandler
    consoleLogger:
        level: DEBUG
        handlers:
          - consoleHandler
        propagate: no
    fileLogger:
        level: DEBUG
        handlers:
          - fileHandler
        propagate: no

root:
    level: DEBUG
    handlers:
      - consoleHandler
