# if you set the time too early in the day, the API might not have the image yet.
time_to_fetch = 08:30:00
app_name = "bingwallpaper.py"
image_dir = "Pictures/BingWallpapers"
background_img_prefix = "background_img"
# resize jpeg quality % defines thew size of the resized image. higher number -> better image, greater file size
resize_jpeg_quality = 89
# trim number of images collected always to this number: for me ~9 years: 9 * 365 = 3285
number_of_images_to_keep = 3285
retain_images = true
# peapix is prefered service, since it allows to download better images from different contriesWIDTH
dl_service = "peapix"
region = "us"

[desktop_img]
enabled = true
# if height or width is configured to not supported size, it will be defaulted to 4K resolution: 3840x2160
width = 3840
height = 2160
# the alternative sizes are not configurable, there are here just for information what is supported
alt_dimention = [ {"width" = 640, "height" = 480}, {"width" = 1024, "height" = 768}, {"width" = 1600, "height" = 1200}, {"width" = 1920, "height" = 1200}, {"width" = 3840, "height" = 2160} ]

[constant]
alt_dl_service = ["bing", "peapix"]
alt_peapix_region = ["au", "ca", "cn", "de", "fr", "in", "jp", "es", "gb", "us"]
bing_url = "http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US"
peapix_url = "https://peapix.com/bing/feed"

[ftv]
enabled = false
set_image = true
ip_address = "192.168.0.119"
port = 8002
# image change frequency in sec
image_change_frequency = 300
# The image size for ftv is stored in the native 3840x2160 (4K) format.
# This cannot be changed, because it is the native resilution for Frame TV
