name: BingWallPaper

on:
    push:
        branches:
            - master

env:
    ENV: prod

jobs:
    Deploy:
        name: Run on ${{ matrix.py }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}-latest
        strategy:
            matrix:
                # os: [ubuntu-latest]
                os: [ ubuntu, macOS, windows ]
                py: [ "3.8", "3.9", "3.10" ]

        steps:
            - name: checkout repo
              uses: actions/checkout@v2
            - name: setup python ${{ matrix.py }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.py }}
            - name: Python Info
              run: |
                echo ""
                echo "------------------------"
                echo "Python version"
                echo "------------------------"
                python --version
                echo ""
                echo "------------------------"
                echo "Python3 version"
                echo "------------------------"
                python3 --version
            - name: install dependencies
              run: make install_test
            - name: install tox-gh
              run: python -m pip install tox-gh
            - name: run unit tests
              run: make test_vff
            # coverage has a problem with windows so not running it if windows OS
            - name: run coverage
              if: "!contains(matrix.os, 'windows')"
              run: make coverage
